### ISSUE TITLE
Unable to install package through devtools 

### ISSUE THREAD

**Issue by yiqunchen** [robohyun66/genlassoinf#1]
Complete error message (R 3.5):

* installing *source* package ‘genlassoinf’ ...
** R
** byte-compile and prepare package for lazy loading
** help
No man pages found in package  ‘genlassoinf’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: S3 methods ‘plot.path’, ‘step_sign_plot.path’, ‘stop_path.path’ were declared in NAMESPACE but not found
**Error: package or namespace load failed for ‘genlassoinf’ in namespaceExport(ns, exports):
 undefined exports: dualpathSvd3**
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/genlassoinf’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/5w/rnh5pvh97d52pstc0p6chdh00000gn/T//Rtmpaf6JJG/file3b876e5ab5ef/genlassoinf_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by sangwon-hyun** [comment]
Could you try again? I updated and checked installation on my computer, seems to work fine.

**Comment by yiqunchen** [comment]
It's working for me now. Thx!
